#!/usr/bin/env Rscript

# plot distances form founder infered by prank to actual founder.
#
# Works of files created by a simulation process to mimic some of
# those that we obtain from the RV217 project.  The RV217 sample ahave
# around 10-12 sequences per sample, all taken from the c2v3c3 region
# gp-120 from the HIV-1 genome.

# install any missing packages
# http://stackoverflow.com/a/19873732/1135316
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ape, dplyr, ggplot2, stringr, Biostrings, readr, tidyr, seqinr, DECIPHER)

setwd("~/src/matsen/hiv-sim/sim.rv217/analysis")

root.id <- function(file) {
    tree <- ape::read.tree(file, comment.char = "")
    return(tree$node.label[1])
}

# Extract the inferred sequence at the root node of PRANK output
#
# 'dir' parameter is a character string naming a directory where the PRANK
# output files can be found.  The directory is expected to have a file
# 'prank.best.anc.dnd' containing a tree generated by PRANK, and a
# file 'prank.best.anc.fas' containing the sequences at each node of
# the tree in FASTA format.
#
prank.sequence <- function(dir) {
    treefile <- file.path(dir, 'prank.best.anc.dnd')
    rootid <- root.id(treefile)
    fastafile <- file.path(dir, 'prank.best.anc.fas')
    fasta <- read.dna(fastafile, format = 'fasta', comment.char = '')
    return(fasta[which(labels(fasta)==rootid),])
}

founder.sequence <- function() {
    fastafile <- file.path('..', '..', 'templates', 'HIV1C2C3.fasta')
    fasta <- read.dna(fastafile, format = "fasta", comment.char = "")
    return(paste(fasta[1,],collapse=''))
}


beast.sequence <- function(dir) {
    #print(file)
    burnin_pct = 0.10
    consensus <- function(seqs) {
        seqinr::consensus(as.matrix(seqs), method = "majority", type="DNA")
    }
    tryCatch({
        read_tsv(file.path(dir, 'ancestralSequences.log'), col_names=c("state", "trait"), skip=3) %>%
        add_rownames() %>%
        filter(as.numeric(rowname) > (n() * burnin_pct)) %>%
        summarize(trait=consensus(trait)) %>% as.character()
    }, error = function(e) {
        as.character(NA)
    })
}


consensus.sequence <- function(dir) {
    tryCatch({
        readDNAStringSet(file.path(dir, 'sample_aln.fa')) %>%
            as.matrix() %>% seqinr::consensus(method = "majority", type="DNA") %>%
            as.character() %>% paste0(collapse='')
    }, error = function(e) {
        as.character(NA)
    })

}
    

beast.distance <- function(dir, model='K80', founder=founder) {
    #print(file)
    burnin_pct = 0.99
    distance <- function(s, model, founder) {
        cat('.')
        alignment <- pwalign(s, founder)
        dist.dna(alignment, model=model)[1]
    }

    n <- tryCatch({
        read_tsv(file.path(dir, 'ancestralSequences.log'), col_names=c("state", "trait"), skip=3) %>%
        add_rownames() %>%
        filter(as.numeric(rowname) > (n() * burnin_pct)) %>%
        select(c(trait)) %>%
        rowwise() %>% mutate(dist=distance(trait, model, founder)) %>%
        ungroup() %>% summarize(dist=mean(dist))
    }, error = function(e) {
        NA
    })
    cat("\n")
    return(as.numeric(n))
}

consensus.distance <- function(dir, model='K80', founder=founder) {
    # calculate a consensus of the input sequences
    tryCatch({
        x <- readDNAStringSet(file.path(dir, 'sample_aln.fa'))
        m <- consensusMatrix(x)
        mymap <- c('-'='ACGT', IUPAC_CODE_MAP)
        s <- consensusString(m, ambiguityMap=mymap, threshold=0.25)
        alignment <- pwalign(s, founder)
        dist.dna(alignment, model=model)[1]
    }, error = function(e) {
        as.numeric(NA)
    })
}




prank.sequence <- function(dir, prank.model='codon') {
    tryCatch({
        dir <- file.path(dir, paste0('prank_', prank.model))
        treefile <- file.path(dir, 'prank.best.anc.dnd')
        rootid <- root.id(treefile)
        fastafile <- file.path(dir, 'prank.best.anc.fas')
        fasta <- read.dna(fastafile, format = 'fasta', comment.char = '')
        root <- fasta[which(labels(fasta)==rootid),]
        s <- paste(root,collapse='')
        as.character(removeGaps(DNAString(s)))
    }, error = function(e) {
        as.character(NA)
    })
}


prank.distance <- function(dir, prank.model='codon', model='K80', founder=founder) {
    #print(file)
    tryCatch({
        s <- prank.sequence(dir, prank.model)
        alignment <- pwalign(s, founder)
        dist.dna(alignment, model=model)[1]
    }, error = function(e) {
        as.numeric(NA)
    })
}


# create a DNAbin object representing a pairwise alignment between two sequences
pwalign <- function(s1, s2) {
    ## Nucleotide global, local, and overlap alignments
    pattern <- DNAString(s1)
    subject <- DNAString(s2)

    # First use a fixed substitution matrix
    mat <- nucleotideSubstitutionMatrix(match = 1, mismatch = -3, baseOnly = FALSE)
    globalAlign <- pairwiseAlignment(pattern, subject, type="global", substitutionMatrix = mat,
                                     gapOpening = 5, gapExtension = 2)

    # extracting the aligned sequences from a pairwiseAlignment object is unncessarily complex.
    # see https://support.bioconductor.org/p/70913/#70966

    seqset <- Biostrings:::.makePostalignedSeqs(globalAlign)[1]
    return(do.call(rbind, lapply(seqset, as.DNAbin)))
}

facet_labeller <- function(variable,value) {
    switch(variable,
           indel=ifelse(value, "With indels", "Without indels"),
           as.character(value))
}

scatterplot <- function() {
    tmp %>% gather(method, dist, starts_with("dist.")) %>%
        mutate(method=sub('dist.','',method)) %>%
        mutate(method=factor(method)) %>%
        filter(fitness=='none') %>%
        ggplot(aes(x=wpi, y=dist, group=method, color=method)) +
        facet_grid(~ indel, labeller=facet_labeller) +
        geom_point(position = position_jitter(w = 0.1, h = 0.1)) +
        scale_color_discrete(name="Method",
                             breaks=c("beast", "consensus", 'pcodon', 'pdna'),
                             labels=c("Beast", "Consensus", 'Prank codon', 'Prank dna')) +
        geom_smooth(method="lm", fill=NA) 
}



boxplot <- function() {

    tmp %>% gather(method, dist, starts_with("dist.")) %>%
        mutate(method=sub('dist.','',method)) %>%
        mutate(method=factor(method)) %>%
        filter(as.integer(as.character(wpi)) < 20000) %>%
        mutate(wpi=factor(wpi)) %>%
        #filter(indel) %>%
        ggplot(aes(x=wpi, y=dist, fill=method)) +
        facet_grid(indel ~ fitness, labeller=facet_labeller) +
        geom_boxplot() +
        scale_fill_discrete(name="Method",
                            breaks=c("beast", "consensus", 'pcodon', 'pdna'),
                            labels=c("Beast", "Consensus", 'Prank codon', 'Prank dna')) 

}



founder <- founder.sequence()

# recursively list files matching 'sample.fa'
files <- list.files(path='../build', pattern="sample\\.fa$", recursive=TRUE)

# The files look like,
# 	"1.0E-5/frequency_noindel/replicate_0/5000/sample.fa"
# break down the path components into seperate columns so the data
# can be filtered appropriately.

df <- as_data_frame(list(dir=dirname(files))) %>% 
    mutate(rate=factor(as.numeric(str_match(dir, "^([^/]+)/")[,2]))) %>%
    mutate(rate=reorder(rate, as.numeric(as.character(rate)), FUN=max)) %>%
    mutate(fitness=str_match(dir, "/([^/]+)_[^/]+/replicate")[,2]) %>%
    mutate(fitness=ifelse(is.na(fitness), 'none', fitness)) %>%
    mutate(fitness=factor(fitness)) %>%
    mutate(indel=is.na(str_extract(dir, "noindel"))) %>%
    mutate(replicate=factor(str_match(dir, "replicate_([0-9]*)")[,2])) %>%
    mutate(replicate=reorder(replicate, as.numeric(as.character(replicate)), FUN=max)) %>%
    mutate(wpi=factor(str_match(dir, "/([0-9]+)$")[,2])) %>%
    mutate(wpi=reorder(wpi, as.integer(as.character(wpi)), FUN=max)) %>%
    mutate(dir=file.path('..', 'build', dir))



tmp <- df
tmp <- tmp %>% rowwise() %>% mutate(dist.pdna=prank.distance(dir, 'dna', 'K80', founder)) 
tmp <- tmp %>% rowwise() %>% mutate(dist.pcodon=prank.distance(dir, 'codon', 'K80', founder))
tmp <- tmp %>% rowwise() %>% mutate(dist.consensus=consensus.distance(dir, 'K80', founder))
tmp <- tmp %>% rowwise() %>% mutate(dist.beast=beast.distance(dir, 'K80', founder))

save(tmp,file="distances.Rda")
load(file="distances.Rda")


png(file="distances.png", width=18, height=12, units = "in", res=300)
boxplot()
dev.off()

# who has the highest disparity between consensus score and prank_dna?

dir <- tmp %>% mutate(difference=abs(dist.consensus - dist.pdna)) %>% arrange(desc(difference)) %>% select(dir) %>% head(1) 

x <- DNAStringSet(c(founder=founder,
                    beast=beast.sequence(dir),
                    pcodon=prank.sequence(dir,'codon'),
                    pdna=prank.sequence(dir, 'dna'),
                    cons=consensus.sequence(dir)))
x <- DNAStringSet(sapply(x, function(x) removeGaps(align=x)))
aln <- AlignSeqs(x)
d <-  dist.dna(as.DNAbin(as.alignment(as.matrix(aln))), as.matrix = TRUE, pairwise.deletion=TRUE)



string1 <- "ACTTCACCAGCTCCCTGGCGGTAAGTTGATC---AAAGG---AAACGCAAAGTTTTCAAG"
string2 <- "GTTTCACTACTTCCTTTCGGGTAAGTAAATATATAAATATATAAAAATATAATTTTCATC"
x <- DNAStringSet(c(a=string1, b=string2, c=string2, d=string2))
x <- DNAStringSet(sapply(x, function(x) removeGaps(align=x)))
class(x)

DNA <- AlignSeqs(x)

m <- consensusMatrix(DNA)
consensusString(m, threshold=0.50)
